copy FolhaDeRosto.jrxml .\midas
copy relAR.jrxml .\midas
copy relARApuracaoBrasil.jrxml .\midas
copy relARApuracaoExterior.jrxml .\midas
copy relARBensDaAtividadeRural.jrxml .\midas
copy relARBensDaAtividadeRuralExterior.jrxml .\midas
copy relARBrasil.jrxml .\midas
copy relARDividas.jrxml .\midas
copy relARExterior.jrxml .\midas
copy relARIdentificacao.jrxml .\midas
copy relARParticipantes.jrxml .\midas
copy relARRebanhoBrasil.jrxml .\midas
copy relARRebanhoExterior.jrxml .\midas
copy relARReceitasDespesasBrasil.jrxml .\midas
copy relARReceitasDespesasExterior.jrxml .\midas
copy relComunicacaoSaida.jrxml .\midas
copy relComunicacaoSaidaDetalhe.jrxml .\midas
copy relDarfAuxilio.jrxml .\midas
copy relDarfAuxilioEmergencial.jrxml .\midas
copy relDarfCodBarra.jrxml .\midas
copy relDarfDoacaoECA.jrxml .\midas
copy relDarfDoacaoEstatutoIdoso.jrxml .\midas
copy relDarfMulta.jrxml .\midas
copy relDeclaracaoAlimentandos.jrxml .\midas
copy relDeclaracaoBensDireitos.jrxml .\midas
copy relDeclaracaoBensDireitosParticipacaoInventarioDetalhe.jrxml .\midas
copy relDeclaracaoConjuge.jrxml .\midas
copy relDeclaracaoContribuinte.jrxml .\midas
copy relDeclaracaoDependentes.jrxml .\midas
copy relDeclaracaoDependentesSaida.jrxml .\midas
copy relDeclaracaoDetalheOutrosRendimentos.jrxml .\midas
copy relDeclaracaoDetalhePensaoAlimenticia.jrxml .\midas
copy relDeclaracaoDividasOnusReais.jrxml .\midas
copy relDeclaracaoDoacoes.jrxml .\midas
copy relDeclaracaoDoacoesECA.jrxml .\midas
copy relDeclaracaoDoacoesEleitorais.jrxml .\midas
copy relDeclaracaoDoacoesIdoso.jrxml .\midas
copy relDeclaracaoEspolioConjugePartilha.jrxml .\midas
copy relDeclaracaoEspolioConjugeSobrepartilha.jrxml .\midas
copy relDeclaracaoHerdeiros.jrxml .\midas
copy relDeclaracaoImpostoPago.jrxml .\midas
copy relDeclaracaoImpostoPagoSimplificado.jrxml .\midas
copy relDeclaracaoInventariante.jrxml .\midas
copy relDeclaracaoInventarianteDecisaoJudicialPartilha.jrxml .\midas
copy relDeclaracaoInventarianteDecisaoJudicialSobrepartilha.jrxml .\midas
copy relDeclaracaoInventarianteEscrituraPublicaPartilha.jrxml .\midas
copy relDeclaracaoInventarianteEscrituraPublicaSobrepartilha.jrxml .\midas
copy relDeclaracaoPagamentos.jrxml .\midas
copy relDeclaracaoRendimentosAcumuladamenteDependente.jrxml .\midas
copy relDeclaracaoRendimentosAcumuladamenteTitular.jrxml .\midas
copy relDeclaracaoRendimentosAcumuladamenteTitularAlimentandos.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveis.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalhe.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalheIndenizacoes.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalheLucro.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalhePensao65Anos.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalhePensaoMolestiaGrave.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalheSemFontePagadora.jrxml .\midas
copy relDeclaracaoRendimentosIsentosNaoTributaveisDetalheTransferenciaPatrimonial.jrxml .\midas
copy relDeclaracaoRendimentosSujTribExclusiva.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFContasDependente.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFContasTitular.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFDependenteIndividual.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFMeses.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFMesesDependente.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFMesesListaDependentes.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFMesesTitular.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPFTitular.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPJComExigibilidadeDependente.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPJComExigibilidadeTitular.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPJDependente.jrxml .\midas
copy relDeclaracaoRendimentosTributaveisPJTitular.jrxml .\midas
copy relDeclaracaoResumo.jrxml .\midas
copy relDeclaracaoResumoSimplificada.jrxml .\midas
copy relDeclaracaoSaida.jrxml .\midas
copy relDeclaracaoSemInfo.jrxml .\midas
copy relDeclaracaoSemInfo2.jrxml .\midas
copy relDeclaracaoTransportesGCAlienBensDireitos.jrxml .\midas
copy relDeclaracaoTransportesGCAlienBensDireitosME.jrxml .\midas
copy relDeclaracaoTransportesGCAlienMEEspecie.jrxml .\midas
copy relDeclaracaoTransportesParcIsenGC.jrxml .\midas
copy relDeclaracaoTransportesParcIsenME.jrxml .\midas
copy relDeclaracaoTransportesSemInfo.jrxml .\midas
copy relDeclaracoes.jrxml .\midas
copy relDemonstrativoImoveis.jrxml .\midas
copy relDemonstrativoMoedaEspecie.jrxml .\midas
copy relDemonstrativoMoedaEspecieDetalhe.jrxml .\midas
copy relDemonstrativoMoveis.jrxml .\midas
copy relDemonstrativoPSoc.jrxml .\midas
copy relNotificacao.jrxml .\midas
copy relNotificacaoCondicoesObrigatoriedade.jrxml .\midas
copy relNotificacaoEspolio.jrxml .\midas
copy relNotificacaoSaida.jrxml .\midas
copy relReciboPortais.jasper
copy relReciboPortais.jrxml .\midas
copy relRendaVariavelDependentes.jrxml .\midas
copy relRendaVariavelFundoInvestimentoDependentes.jrxml .\midas
copy relRendaVariavelFundoInvestimentoTitular.jrxml .\midas
copy relRendaVariavelGanhosLiquidosPerdas.jrxml .\midas
copy relRendaVariavelItemGanhosLiquidosPerdas.jrxml .\midas
copy relRendaVariavelItemGanhosLiquidosPerdasDependente.jrxml .\midas
copy relRendaVariavelQuadroImpostoPagar.jrxml .\midas
copy relRendaVariavelTitular.jrxml .\midas
copy subAdquirentes.jrxml .\midas
copy subAjuste.jrxml .\midas
copy subAliquotaEfetiva.jrxml .\midas
copy subAliquotaEfetivaValores.jrxml .\midas
copy subApuracaoAmbasMoedas.jrxml .\midas
copy subApuracaoCustoAquisicaoImoveisBrasil.jrxml .\midas
copy subApuracaoCustoAquisicaoImoveisExterior.jrxml .\midas
copy subApuracaoCustoAquisicaoImoveisExteriorAmbasMoedas.jrxml .\midas
copy subApuracaoEmReaisAlienacaoAPrestacao1.jrxml .\midas
copy subApuracaoEmReaisAlienacaoAPrestacao2.jrxml .\midas
copy subApuracaoEmReaisAlienacaoAVista1.jrxml .\midas
copy subApuracaoEmReaisAlienacaoAVista2.jrxml .\midas
copy subApuracaoFinalAmbasMoedas.jrxml .\midas
copy subApuracaoFinalGanhoImovelExtAmbasMoedas.jrxml .\midas
copy subApuracaoFinalGanhoImovelExtMoedaEst.jrxml .\midas
copy subApuracaoFinalGanhoImovelExtMoedaNac.jrxml .\midas
copy subApuracaoFinalMoedaEstrangeira.jrxml .\midas
copy subApuracaoFinalMoedaNacional.jrxml .\midas
copy subApuracaoGanhoImovelBrasil.jrxml .\midas
copy subApuracaoGanhoImovelExtAmbasMoedas.jrxml .\midas
copy subApuracaoGanhoImovelExtMoedaEst.jrxml .\midas
copy subApuracaoGanhoImovelExtMoedaNac.jrxml .\midas
copy subApuracaoMoedaEstrangeira.jrxml .\midas
copy subApuracaoMoedaEstrangeiraAlienacao1.jrxml .\midas
copy subApuracaoMoedaEstrangeiraAlienacaoPrestacao1.jrxml .\midas
copy subApuracaoMoedaEstrangeiraAlienacaoPrestacao2.jrxml .\midas
copy subApuracaoMoedaNacional.jrxml .\midas
copy subApuracaoMovelBrasil.jrxml .\midas
copy subAquisicaoBrasil.jrxml .\midas
copy subAquisicaoExterior.jrxml .\midas
copy subAquisicaoExteriorAmbasMoedas.jrxml .\midas
copy subCalculoAPrazoBrasilDetalhe.jrxml .\midas
copy subCalculoAPrazoBrasilMovelPSocDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorAmbasMoedas.jrxml .\midas
copy subCalculoAPrazoExteriorAmbasMoedasDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorAmbasMoedasParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorAmbasMoedasParcelas.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaEst.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaEstDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaEstParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaEstParcelas.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaNac.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaNacDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaNacParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoExteriorMoedaNacParcelas.jrxml .\midas
copy subCalculoAPrazoImovelBrasil.jrxml .\midas
copy subCalculoAPrazoImovelBrasilDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelBrasilParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelBrasilParcelas.jrxml .\midas
copy subCalculoAPrazoImovelExteriorAmbasMoedas.jrxml .\midas
copy subCalculoAPrazoImovelExteriorAmbasMoedasDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelExteriorAmbasMoedasDetalhe_copia.jrxml .\midas
copy subCalculoAPrazoImovelExteriorAmbasMoedasParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelExteriorAmbasMoedasParcelas.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaEst.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaEstDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaEstDetalheEnquadramento.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaEstEnquadramento.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaEstParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaEstParcelas.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaNac.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaNacDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaNacDetalheEnquadramento.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaNacEnquadramento.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaNacParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoImovelExteriorMoedaNacParcelas.jrxml .\midas
copy subCalculoAPrazoMovelBrasil.jrxml .\midas
copy subCalculoAPrazoMovelBrasilDetalhe.jrxml .\midas
copy subCalculoAPrazoMovelBrasilParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoMovelBrasilParcelas.jrxml .\midas
copy subCalculoAPrazoPSoc.jrxml .\midas
copy subCalculoAPrazoPSocDetalhe.jrxml .\midas
copy subCalculoAPrazoPSocParcelaDetalhe.jrxml .\midas
copy subCalculoAPrazoPSocParcelas.jrxml .\midas
copy subCalculoAVistaBrasil.jrxml .\midas
copy subCalculoAVistaExterior.jrxml .\midas
copy subCalculoAVistaImovelExterior.jrxml .\midas
copy subCalculoAVistaMovelExterior.jrxml .\midas
copy subConsolidacaoBrasil.jrxml .\midas
copy subConsolidacaoDeAlienacao.jrxml .\midas
copy subConsolidacaoExterior.jrxml .\midas
copy subCustoAlienacao.jrxml .\midas
copy subCustoAquisicaoImoveisBrasil.jrxml .\midas
copy subCustoAquisicaoImoveisExtAmbasMoedas.jrxml .\midas
copy subCustoAquisicaoImoveisExtMoedaEst.jrxml .\midas
copy subCustoAquisicaoImoveisExtMoedaNac.jrxml .\midas
copy subCustoAquisicaoPSocietarias.jrxml .\midas
copy subEnderecoBrasil.jrxml .\midas
copy subEnderecoExterior.jrxml .\midas
copy subEspecie.jrxml .\midas
copy subEspecificacaoBemDireitoEstrangeira.jrxml .\midas
copy subEstrangeira.jrxml .\midas
copy subEstrangeiraAquisicao.jrxml .\midas
copy subGanhoCapitalImoveisAmbasMoedas.jrxml .\midas
copy subGanhoCapitalImoveisBrasil.jrxml .\midas
copy subGanhoCapitalImoveisExterior.jrxml .\midas
copy subIdentificacaoAdquirenteMoeda.jrxml .\midas
copy subImpostoPagoExterior.jrxml .\midas
copy subMensagemMudancaEnquadramento.jrxml .\midas
copy subMista.jrxml .\midas
copy subOperacaoBrasil.jrxml .\midas
copy subOperacaoExterior.jrxml .\midas
copy subOperacaoImovelExterior.jrxml .\midas
copy subOperacoesMoedaEstrangeira.jrxml .\midas
copy subPerguntas.jrxml .\midas
copy subPerguntasImovel.jrxml .\midas
copy subPerguntasPSoc.jrxml .\midas
copy subReaisAlienacaoDeBensDireitosOuAplicacoesFinanceiras.jrxml .\midas
copy subReaisAquisicao.jrxml .\midas
copy subReal.jrxml .\midas
copy subRelGCAP.jrxml .\midas
copy subRelGCME.jrxml .\midas
